CRITICAL - 2024-01-04 12:26:51 --> Call to a member function table() on null
in APPPATH/Models/User.php on line 19.
 1 APPPATH/Controllers/Users.php(18): App\Models\User->__construct()
 2 SYSTEMPATH/CodeIgniter.php(915): App\Controllers\Users->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
 3 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 12:27:46 --> Undefined property: App\Controllers\Users::$userModel
in APPPATH/Controllers/Users.php on line 29.
 1 APPPATH/Controllers/Users.php(29): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Users::$userModel', '/Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php', 29)
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 12:29:09 --> Call to a member function table() on null
in APPPATH/Models/User.php on line 19.
 1 APPPATH/Controllers/Users.php(29): App\Models\User->__construct()
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 12:31:01 --> Call to a member function table() on null
in APPPATH/Models/User.php on line 19.
 1 APPPATH/Controllers/Users.php(29): App\Models\User->__construct()
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 12:32:21 --> Call to undefined method App\Models\User::insertNewUser
in SYSTEMPATH/Model.php on line 876.
 1 APPPATH/Controllers/Users.php(30): CodeIgniter\Model->__call('insertNewUser', [...])
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:31:07 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:31:07 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:35:26 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:35:26 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:39:59 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:39:59 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:40:02 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:40:02 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:40:56 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:40:56 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:41:34 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:41:34 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:42:55 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:42:55 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:42:56 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:42:56 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:45:12 --> Error connecting to the database: mysqli_sql_exception: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'TCS', 3306, '', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No such file or directory in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#4 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#5 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#10 {main}
CRITICAL - 2024-01-04 13:45:12 --> Unable to connect to the database.
Main connection [MySQLi]: No such file or directory
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 3 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 4 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:46:10 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 13:46:10 --> Unknown column 'user' in 'field list'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 2 APPPATH/Models/User.php(29): CodeIgniter\Database\BaseBuilder->insert('user')
 3 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 13:47:10 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(30): CodeIgniter\Database\BaseBuilder->insert('user')
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(30): App\Models\User->insertNewUser(Array)
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->add()
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 13:47:10 --> Unknown column 'user' in 'field list'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `phone`, `password`, `active`, `user`) VALUES (:username:, :email:, :phone:, :password:, :active:, :user:)', [...], false)
 2 APPPATH/Models/User.php(30): CodeIgniter\Database\BaseBuilder->insert('user')
 3 APPPATH/Controllers/Users.php(30): App\Models\User->insertNewUser([...])
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 13:56:03 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::or_where()
in APPPATH/Models/User.php on line 24.
 1 APPPATH/Controllers/Users.php(30): App\Models\User->get([...])
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 14:01:56 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::rows()
in APPPATH/Models/User.php on line 26.
 1 APPPATH/Controllers/Users.php(30): App\Models\User->get([...])
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->add()
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:02:20 --> Cannot use object of type stdClass as array
in APPPATH/Views/gerenciador/dashboard/users/index.php on line 28.
 1 SYSTEMPATH/View/View.php(228): include()
 2 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/index', [], true)
 4 APPPATH/Controllers/Users.php(17): view('gerenciador/dashboard/users/index', [...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->index()
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:11:59 --> Undefined property: stdClass::$level
in APPPATH/Views/gerenciador/dashboard/users/index.php on line 30.
 1 APPPATH/Views/gerenciador/dashboard/users/index.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$level', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/index.php', 30)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/index.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/index', [], true)
 5 APPPATH/Controllers/Users.php(17): view('gerenciador/dashboard/users/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->index()
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:12:01 --> Undefined property: stdClass::$level
in APPPATH/Views/gerenciador/dashboard/users/index.php on line 30.
 1 APPPATH/Views/gerenciador/dashboard/users/index.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$level', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/index.php', 30)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/index.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/index', [], true)
 5 APPPATH/Controllers/Users.php(17): view('gerenciador/dashboard/users/index', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->index()
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:18:18 --> Undefined variable $user
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(50): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:19:37 --> Cannot access offset of type string on string
in APPPATH/Models/User.php on line 23.
 1 APPPATH/Controllers/Users.php(51): App\Models\User->get('3')
 2 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 3 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 4 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:20:57 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:20:57 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:21:44 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:21:45 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:21:45 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:21:45 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:22:17 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:22:24 --> Attempt to read property "level" on array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "level" on array', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:22:46 --> Undefined array key "level"
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "level"', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:22:48 --> Undefined array key "level"
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 64.
 1 APPPATH/Views/gerenciador/dashboard/users/edit.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "level"', '/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php', 64)
 2 SYSTEMPATH/View/View.php(228): include('/Users/rlferrazza/Documents/skeleton/app/Views/gerenciador/dashboard/users/edit.php')
 3 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 5 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 6 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
CRITICAL - 2024-01-04 18:22:56 --> Cannot use object of type stdClass as array
in APPPATH/Views/gerenciador/dashboard/users/edit.php on line 13.
 1 SYSTEMPATH/View/View.php(228): include()
 2 SYSTEMPATH/View/View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH/Common.php(1190): CodeIgniter\View\View->render('gerenciador/dashboard/users/edit', [], true)
 4 APPPATH/Controllers/Users.php(52): view('gerenciador/dashboard/users/edit', [...])
 5 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('3')
 6 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:23:01 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:23:01 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:23:24 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:23:24 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:23:39 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:23:39 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:23:39 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:23:39 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:24:01 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:24:01 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:24:02 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:24:02 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:24:21 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:24:21 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
ERROR - 2024-01-04 18:24:39 --> mysqli_sql_exception: Unknown column 'images' in 'where clause' in /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /Users/rlferrazza/Documents/skeleton/system/Database/MySQLi/Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/rlferrazza/Documents/skeleton/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/rlferrazza/Documents/skeleton/system/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/rlferrazza/Documents/skeleton/app/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/rlferrazza/Documents/skeleton/app/Controllers/Users.php(51): App\Models\User->getById('images')
#6 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
#7 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 /Users/rlferrazza/Documents/skeleton/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Users/rlferrazza/Documents/skeleton/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /Users/rlferrazza/Documents/skeleton/system/Commands/Server/rewrite.php(47): require_once('/Users/rlferraz...')
#11 {main}
CRITICAL - 2024-01-04 18:24:39 --> Unknown column 'images' in 'where clause'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `id` = images', [], false)
 2 APPPATH/Models/User.php(31): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH/Controllers/Users.php(51): App\Models\User->getById('images')
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Users->edit('images', 'icons', 'favicon.ico')
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/Users/rlferrazza/Documents/skeleton/public/index.php')
